### ISSUE TITLE
Filenames are case sensitive in Linux filesystem

### ISSUE THREAD

**Issue by franckinux** [embedded-office/canopen-stm32f4xx#2]
In file src/CMakeLists.txt on line 37 : driver/stm32f4xx-hal/drv_nvm_fmpi2c1_at24**C**256.c  and
in file on line 21 : src/driver/stm32f4xx-hal/drv_nvm_fmpi2c1_at24**C**256.c
But in the reposotory, the file is  : src/driver/stm32f4xx-hal/drv_nvm_fmpi2c1_at24**c**256.c

**Comment by michael-hillmann** [comment]
Thank you for highlighting this issue. This is a relict and needs to be lower case everywhere.
